### ISSUE TITLE
Compilation fails when using most recent HPX

### ISSUE THREAD

**Issue by G-071** [STEllAR-GROUP/octotiger#60] opened 2018-02-11 18:14 UTC
I have problems building the current master branch of octotiger using the current master branch of HPX (98effdc7e9b8b2ac39da4a023aaa079ffe81c4ee). 

I get a lot compilation error about seq when I try to compile octotiger, for example:

> /home/daissgr/current-oct/src/hpx/hpx/parallel/datapar/transform_loop.hpp: In static member function ‘static typename std::enable_if<(((! hpx::parallel::util::detail::iterators_datapar_compatible<InIter1, InIter2>::value) || (! hpx::parallel::util::detail::iterator_datapar_compatible<Begin>::value)) || (! hpx::parallel::util::detail::iterator_datapar_compatible<InIter2>::value)), std::pair<_U1, _U2> >::type hpx::parallel::util::detail::datapar_transform_loop<Iterator>::call(InIter, InIter, OutIter, F&&)’:
/home/daissgr/current-oct/src/hpx/hpx/parallel/datapar/transform_loop.hpp:130:45: error: ‘seq’ is not a member of ‘hpx::parallel::v1’
                 return util::transform_loop(parallel::v1::seq,

The compilation of hpx itself does not show any errors whatsoever. 

This problem does not occur when using a slightly older HPX commit from January 22 
( 29da281b87cfa1171b42f5e2f22caa29b3c4be2d)

I am using gcc 5.4.0 and boost 1.63. Full compilation log:
[octotiger-compilation-log.txt](https://github.com/STEllAR-GROUP/octotiger/files/1714666/octotiger-compilation-log.txt)

**Comment by hkaiser** [comment] 2018-02-11 18:53
`seq` has been moved to `hpx::parallel::execution::seq`, if that still fails we'd need to have a closer look...

**Comment by G-071** [comment] 2018-02-11 21:46
The string `seq` occurs only once within the source code of octotiger (grid_fmm.cpp line 23) and there it is already used as `hpx::parallel::execution::seq`. Hence my confusion!

I tracked to problem back to the inclusion of `#include <hpx/include/parallel_transform.hpp>` in the file taylor.hpp. 
If I just remove this include and change nothing else, Octotiger compiles (and runs) correctly. Apparently this header is not used at all (at least with my configuration of octotiger), yet its mere inclusion causes compilation errors!

After this workaround I got curious and quickly added a new  dummy cpp file to octotiger which just consists out of:
`#include <hpx/include/parallel_transform.hpp>
int dummy(void) {
  return 1;
}
`
Compilation for this file fails as well! (same error messages about `seq`)

**Comment by hkaiser** [comment] 2018-02-12 20:25
@G-071 I'm not able to reproduce the issue. Could you please post the full error log somewhere? Please also provide your HPX configuration file `<hpx_build_dir/hpx/config/defines.hpp`.

**Comment by hkaiser** [comment] 2018-02-12 22:03
@G-071 that should be fixed now, pls see https://github.com/STEllAR-GROUP/hpx/pull/3168 and verify whether this resolves the issue.

**Comment by G-071** [comment] 2018-02-12 22:49
I tried rebuilding my entire toolchain using the branch containing the fix. It fails at the cmake step of hpx. I have attached the output of my buildscript and the cmake log:

[complete-build-log.txt](https://github.com/STEllAR-GROUP/octotiger/files/1717962/complete-build-log.txt)
[CMakeOutput.log](https://github.com/STEllAR-GROUP/octotiger/files/1717990/CMakeOutput.log)

Do you still need a full error log and the HPX configuration for when I build with the master branch?

**Comment by hkaiser** [comment] 2018-02-12 23:18
Sorry for that - should be fine now. This time for real ;-)

**Comment by G-071** [comment] 2018-02-13 00:04
That seems to have done the trick - it works now. Thanks for the help!

**Comment by hkaiser** [comment] 2018-02-13 15:25
This has been fixed by merging STEllAR-GROUP/hpx#3168

**Closed by hkaiser** 2018-02-13 15:25 UTC
